#include <iostream>

using namespace std;

int main()
{
	cout << "\n";
	cout << "Revisa el codigo. \n";
	cout << "\n";
	
 } 

//                                                                                                                                                                                          .lk0NNk'....',;;:cloodxkkkkxxddl;'cdxxxxddooolllcc:;;;;,,''''....'',,,,,,,;;:kNNO;.                               
//                                                                             .... ....   ...   ...          .,'                   .                                 .;.                 .o0KXKkllooddddxxxdddddddddddoolcclllllll:;;;;,,,''...............'',,,,,,,;;xNW0;.                               
//                                                                              .:Ok, .d0l.  ,xl'',;;,'';;,''''.:Kk...               ,Oc  '.                           .lXo                 ,xxdoool:ccclcllooooolc::::;;,,,''''......''........................'''''''';xNW0;.                               
//                                                                                oXc  ;KO'..cd''::cc;,:ccc:;:c;cKk,,;;,,,.  .'..,,. 'Ol.o0o.     .,..,,'..';'.  .'',.  ;Xo .,,.  .',,.     .:lcll:;:llcolclccl;.,;;;,..';;,:;.,;;:,....................................,dXW0;.                               
//                                                                                .kK,.lOKd.;x;.oxclOO:,::,'ox:'lXk.,xo;;dk:.oXx;cOx. '..dXc.    .oXx;cOW0l;o0o 'kl'dK; ;Xd'll,..ldclOO,    .oxclO0:;00llclKkcl;:x:':xx,'kXocclkl,ol..'.......................''........'lKW0:.                               
//                                                                                 ,0koo'oKddc.cKo';:c;';;.cXo..,Ox.oK:.',OO.;Kl  d0,    lK;      :Xl  oMK; .Ok..cc,dNc ;KK0o.  :Ko.'';'....;Ko',;:..kO.  ,0o  '0x...cNo o0, .'dkdo:..........................''''''''''';oXKc.                               
//                                                                                  cXO;.'kNo'.;OO:,;l;';,.;0O;.,0O'cKd'.;Od.:Xl..d0,    lXc.     :Xl  oMX; .Ox.cKl.oNo.:Xd:kx' 'OO;.':,....'OO:',c'.kO.. ,Ko. .x0:..l0: o0,..,;.;OO'.......................''',,,,,,,,;;cONXl.                               
//                                                                                ..,lc',':o,',',odol:'',,'.;oo::do,.;oc,:c,.:xc',ld;.   'ol,.    ;d:..cxd,.'ol.'ol;:ol';dc.,dl'..ldol;......'ldol;.'lo,..;dl....cl;,c;..ld;..;o;'c:.....................'''',,,;;;;;;;;;lKWNd..                              
//                                                                               .,:;,;;;;,,,,,'......',,'''..............',,,'',;,,,,.                                                .............................................''''''''',,,,;;;,,;;;;;;;;;;;;::::;:;l0WNx'.                              
//                                                                               .;;;;;;,,,,,''......',,,,,,,,,,,''.''''''',,,;;;;::::;'.                                              ...............................'''',,,,;;;;;;;:::::cccccccccccccccccccllllloolc::;c0NNk'.                              
//                                                                               ';;,,,,,'''''.....',;;;;;;;:::::;,,,,'''''''',,,;;;;;;;.                                              ............................'''''',,,;;;:::ccccllloollllccclllllllloooooooooooc:::cONWO,.                              
//                                                                              .';,,,,''''''.....',;:::::ccllollcc:;;;;,''''''''',;;;;:,.                                             .........................'''',,,,,;;;;::cclllllllcc::;;;;;:::::::::::::::cccccccccl0WWO,.                              
//                                                                              ',,''''''........',::clllloodddoollllc:::;,''...'',,,;;;;.                                             .'..........'''''''',,,,;;;;;::::cccclllllllllc::;,,,,,,,,,,;;;;;;:::::::ccccccclllONWO;.                              
//                                                                             .',''''''.........';clooodxkkkOkkxdddolcccc;'...'''',,,,;;'.                                            .,;,',,,,,;;;;;;;;;;;;:::::::ccclllllllcc::;;;,,,,,,,,,,,,;;;:::ccccccc::::ccclloloONW0:;coo,.                         
//                                                                              .'''''........'.',;:ccc::coxkO00OOOOkxdool:,...'''',,,,,,'.                                            .;c::;;:::::::::ccc:::cccccllccccccc:;,,,''',,,,,,,;;:::ccllllooooolcccclllllloooooONWXOXWWXl..                        
//                                                                              ..'.''........'',;:ccodxkxdoodOOkkkOOOkkxoc,'..''''',,,,,'.                                            .;ccccccccc::::::::::::::::;;,,,,,,,,,,,,,;;::cccclllllloooooddoodddddxxxxxxxddddddONWN0KN0kl..                        
//                                                                              ..............',:lodddoodxxdookOxolc:cclll:,'''..''''''''..                                            .:llllcc:;;,'',,;;;;:::::;;;;:::::::ccclllloooodddoooooodddxxxxxxxxkkkkkkkkkkxdddddONWN0KXkxx,.                        
//                                                                              ..............':odkkkkxxxkkkxxOOxolllollcc;,''......'''''.                                              :oc::;,,'''',,;;::cccccccccccllllcccccclllooodddddxxxxxxxO00OxxxxkkkkkOOOOO0OxddddONWX00NWWKc..                       
//                                                                              ........'''..,:loxkkOOO000OkxkOOkkxdooddol;'''......''''..                                              ,;,'''''',,;;:::cc::::::::ccc::::::::cclodddddooooooddddx0KKOxxxkkkkOO00KKKKKOxdddONWX0OXWWNd'.                       
//                                                                               .......,,'',:cloddxkOOOOOxxxkOOkO00Okxxxd:,'''.......''.                                                .',,,,;;::;;;;;:;;;;;;;;cxOkocc:ccccllooooooollllooddddxxkkkxxxkkO00KKKKKKKKK0kxdkXWX0OKNWWk,.                       
//                                                                               .......;:;::ccllooxkOOkxdddxO0OkkO00OOkkd:,,'''''......                                                  .',,,;;,,',,,,;;;;:::::coddl::::clllllloooooodddxxxxxkkOOOO000KKKKKKKKKKKKKKOxxdkXWNOk0XWW0:..                      
//                                                                                ......,oolccloolodxkkxdl:;:coodk00OOOkxo:,,''''......                                                  ...''''',,,;;;;;;;;::::::cccllcclodddddxxxxxkkkOO000KKKKKK0KKKKKKKKKKKKKKKK0kxdxdkXNXOkOXWWXo..                      
//                                                                                .......':::cllllodxxxkkxddoollokO0OOkxoc;,,'.........                                                  ',',;;;:::cccccccccclllllooodxdddxxkkkkOOOO000000000000000OO00OkkkOkxdxkkkxddddddkKWXkxkKNWNx'.                      
//                                                                                 ..... ..';:clllooollooodxxxkkkOOOkkdol:,'''.......                                                   .;:;::::ccccllllloooooooddxxddoc;:odddddxkkxddxdoooc:cccc:;,;c:,............:dddxdxKWNkdkONWWO;..                     
//                                                                                  .......';:clllol:,'''',:cldxxkkkxdollc;,'.......                                                    .;c:c:,,:ccccccclolccccloool;...  .......''.....                            ;oddddx0NNkoxkXWWKc..                     
//                                                                                  ......';;::ccclloollllc:,',:codddoolllc,.......                                                      ,:;,.........  ...    ....                                   ..  ..        ,ooooooONNklxk0NWNd..                     
//                                                                                   ...,::::::::cloddddxkxxxolc:coooolc:;,......                                                         ..                                                                        .clllllkNWkcdkONWNk,.                     
//                                                                                    .ckkl:::::cloodddxxxxxddxxdlllllc:,.....                                                            .                                                                 ..     ..,;:cccxXNO:lkkXWWK:.                     
//                                                                                   ,dOOkxl::cclodddddxxxxxdddddlcccc;,.....                                                            ...                                                       .....................'',dXWO;:xx0NWXo.                     
//                                                                                .'cO0OOkkxl::clddddddddddddddddolcc;'....                                                              ..                        .......           ................'''''''','''''''''''',dXW0;,dxONWNx'                     
//                                                                            .,cdkO0K00OOOOkl::lodddoolllloddxxxol:;....                                                                 .          ............................''''',,,,,,,;;;;;;;;;,,,,,,,,,,,,,,,,,,,',dXN0;.oxkXNNO;.                    
//                                                                     ..,;cok0XNXXKKKK00OOOOko::cooolllcllodddddl;'.                                                                     ''........................'''''',,,,,,;;;;;;;;;:;;::::::::cc::::::::;;;;;;;,,''',oKN0;.cxxKNWKc.                    
//                                                                   .;dOKXNNNNNXXNXKKXK000OO0Odc;:::cccclooooolc,.                                                                       ,;.............'''''''''''',,,,,,;;;;:lc:c:::::::::::::::::::::::::::::::::;;;;;;dKN0:.;ddONNNx'                    
//                                                                .;lkXNXXNNNNNNNNXKKKXXK0000000xc,'',;;::cclccldd:..                                                                     ,:'......''...''''''''''',,;;;;;;;;;;;;,,:;;;;;,,,,,,,,,,,,;;;;;;;;;;;;;;;;;,,;:co0NKc.,odkXNNKc.                   
//                                                             .;d0XNXNNNNNNNNNNNNXKKXXXXKK0000XKkc,'',,,;:ccccoxkkd:.                                                                    ';........'''',''''',,,;;;:::::::::;;;,'''''''',,''''''''''''''.....''''''''',;clo0NKl..ldxKNNKc.                   
//                                                           .;x0KKXXNNNNNNNNNNNNNXXKXXNXXKKK00kddddoc;;:cllolcloxkOko,.                                                                  .'......''',,:l:;;;::::::::::;,,,,'''''''''''',:;'''''...''''''''.............,:clONXo..;ddONN0:.                   
//                                                          .lxO0000000KXNNNNNNNNNXXKKXNXXKKOdc:clokkxdlllooooolodxkOOkl'.                                                                ....'',,,,,;;;:;;;;::;;,,,,'''.........''''',,,;;,,,,'.......''''...........',,;:ckNXd. .odkXNKl.                   
//                                                         .lxxxxk000K00O00KXNNNNNNXXXXXXK0koc::coxxkOOdoooooddxdddxkO0KOo'.                                                              ...':cc::;;;;;;;;;,,,''.............'...''''''',,,''.............................;xXXd. .cdxKNKo.                   
//                                                        .ldxkkkkkOO0KXKK0OO0KXNNNXXXXXX0OOOOkkddxO0K0kxdddddodkkxkkO0XNXl..                                                             .;;,;clllloollc:,''.''''............'''..........''..............................'dXXx.. ;ddONKd'                   
//                                                       .coloxkOO0000KKXXXXK0O0KXXXXXXXXXXNNNNNNKOkO00kkkxdddllxkdl:::xXXo..                                                             .;c:,';;;:::c::,''',,,''.......................................''................,dKXx'. .odkXKx,                   
//                                                      .;oooodkOO00KKKKKXXXXXXK00KXNXXXXXNNNNNNNX0OkOOxkkkxxdocldl:clldXXOc..                                                            .,::;.......'...................................''''',,....',;;,'................'oKNk,. .cddKKx;.                  
//                                                      'looodxO0000KKKKKKKXXXXXX00KNNXXXXXXNNNNNNX0kkkxxkkkkxxdOXKXXX0xk0KKl..                                                            ';;,'..................................'''',,,;;;:,';cccccc::::;;,,'............'l0Xk,.  ;ddOKx:.                  
//                                                     .clllllodkKKKKKKXXXXKKXXXXX00XXXXXXXXNNNNNNXKOOOOkkkkkkxOXNXNNNXOk0KX0:..                                                           .;,,'..............................',:cllllllllccc' .;llc:::::::::::;'...........c0XO,.. 'odk0xc.                  
//                                                    .;lllooooddxOKKKKXXXXXXKXXXXX00XXXNXXXNNNNNNNX0OO00kkkkkk0NNNXK0OOO00KXk;.                                                           .,,'............................',;clllcc:::ll:;;lc..;:cc::::::::::;:,..........'c0XO;.. .cdxOxc.                  
//                                                    .clllloodddxxxOKXXXXXXXXXXXXXK0KXXNXXXXXNNNNNNK0kxOOkkkkk0NNNKOkOOOOOKNXd,.                                                          .'''...........................':cccccc:::::;:;;;;;'.,;;;;;::::::;;;'.....'',,,,,:OX0c.. .;odkxc'                  
//                                                   .;lllolloddxkkkkkO0XXXXXXXXXXXXK00KXXXKXXNNNNNNNX0kk0Okxkk0XNXOOOOOO00XNX0o..                                                         .''','...',,,,,''..............';::::::::::;;;;;;;;,,,;;;:::::;;;,'...',,,,,,,,,';kX0l.   'ooddc'.                 
//                                                  .,lllloooloodxkOOOOkO0KXXXXXXXXXK000XXKKXXNNNNNNNNX0xxOkxxxOXX0OOO0KXXNNNXXk;..                                                        .',,,,,',,,,,,,,,,,,,,,,,,,,;;;;:::::::::::::::::::::::::;;;;;;,,'.',,,,,,,,,,,,';xK0l.   .loodc'.                 
//                                                 .:llllloddooodxkOO000OO0KXXXXXXXXXK00KKKKXXXNNXNNNNNX0xxOkxdkK0OO0KXXXNNNNXX0l..                                                         .......''''''''''',,,,,,',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;,,,,,dKKc.   .:oloc'.                 
//                                                .odclllclxkxdddxkO00000000KXXXXXXXXK0000KKKKXNXXNNNNNNX0kkOkdx0OOKXXXXXNNNNXXKd'.                                                                ,cccccccc::::::cc:::cccccccccccc::cc:::::::::::;;;;;;;;;;;;;,,,,''....'',oxo;.     ,ollc,.                 
//                                                :kxooollldOOxddxxkO00KKKK00KXXXXXXXXK0000KKKXXXXXNNNXXXX0OOkddO0KXXXXXXXNNXXKKd'..                                                              .',,,'....,,,,'..........''''''''''',,,,,;;;;;;;;;:;;;:::::::::::;,'. ...;kO;       .llc:,.                 
//                                               .:oloooolclxOOkxxxkO00KKKKKKKXXXXXXXXXK000KKKXXXXXXXXXXXXX0OkddOXXXXXXXXXXXXXK0o...                                                                       .';,,,.                                                     .,;;lkx,       .:l::,.                 
//                                                ,l:coooolccdO0OkkkO00KKKKKKKXXXXXXXXXK000KKKKXXXXXXXXXXXNXKOxdOXXXXXXXXXXXXK0Ol...                                                                        .,,;,.                                                      ......         ,l:;'.                 
//                                                .cl:codool::cdkkOO000KKKXXKKKXXXXXXXXK00KKKKKXXXXXXXXXXNNNXKkxOXXXXXXXXXXXXKOkc...                                                                        .,;;;'.                                                                    .::,'.                 
//                                                 .cl,;loolc::clodxkO000KKKKKXXXXXXXXXXKKKKKKKKXXXXXXXXXXNNXX0k0XXXXXXXXNNXK0Okd'..                                                                         ',,;;;;;;:::::::;;;,,''''''''''...............                             ;:'..                 
//                                                  .;c;;coolcccloodxOOOOOO00KKKKKKKKXXXXXXKKKKKKXXXXXXXXXNNNX0O0XXXXKKXNNNXK0OOk:.                                                                          .,,,,,,,,,;;;:::::::::ccccclllllllllloooooooooooooooolooollllcc::::;;;,''..;;'..                 
//                                                 .;;;:;,:lol:cllodkOOOO0000000000KKKXK0OKKKKKKKXXXXXXXXXXNNX0OKXXK0KXXNNNXK00OOo'.                                                                         .',,,'.      ...................'''''',,,,;;;;::cccllooddxxxkkkkkkkOOOkkkxdl:'..                 
//                                                 .cllcc,.;ooc:clokOOkOO000OOO000K00OOOOkkO000KKKXXXXXXXXXNNKOO000O0XXXXXXKKK0OOk:.                                                                          .,,,'..'...                                 .............''''',,,,;;;::ccc:;'..                 
//                                                 .;:c:::,.;llccldkkkkOOOOOOO000KK00OOO000O000KKKKKXXXXKKXXNKOOOOO0XXXXXXXKK0OO00o'.                                                                         .',,,,;:,,,..                                                              .'..                 
//                                                 .;;colll;.,cl:cdkxxkkkkkkOO00OkkkOOO0000KKXKKKKKKKKKKKKKXXKOOO0KXXXXXXXX00OkO00k:..                                                                        .';;,'''''''''''''''....................                                   .'..                 
//                                                 .;::ldddo;.':c:loddxxkkkkOOOO00KKKKOO00KKXXKK0KKKKKKKKK0KK0O0KKXXXXXXXX0OOkxkOOOxc..                                      .         .         ..,.          ,llc;;,,,'..............''''',,,,,,,,,,,,,,,,,,,,,,,;;;;,,,,'''.......... ...                  
//                                                 .;:,;coddo;..:::codxxxxkO000KKKKKKOk0KKKXKKK0KXXXXXXXXKKKKK00KXXXXXXXK0kkkkkkOOOKXo.....        .......  . .',.....      ,:'....    ...',,''.. .''',,,;;,,,,:loddxdl;.                    ...............''',,;;::cclllloooddddddddoc,...                  
//                                                  ,c:;;;cooo;..,;:cloddxk000O000KK0kk0KKKKK0OOKXXXXXXXXXXXXXK0OOOOOOOOOkxxxxxkkkkO0xccllcc:;;,''...',,''',,''''',;;.. ....',''......'''''''....,;:clooooollxO0KKKXNNKo,..                                             .........''',,,,....                  
//                                                  .clcc:;;:loc'.';:cloox0K0OO00000OkO00000OO0KXXXXXXXXXXXXXX0OkkkkkkkkkkkkkkkkkkkOkkOOOOOOOOkkxdolc::;;,,,''''',,,....',:cc::;:::::::;;;,,,,;:cclooollllokKNWWWWWWWWKdol'                                                             .,..                  
//                                                   .coooolcclc;...,:clldOKOkO000OOOOOOOOOkdodkKXXKKKKXXXXKK0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkxxddolc:;'....';cllllllllloooollllddlcccllllllllloddkKNNNNNNWWWXOxkd'                                                            .cc'.                  
//                                                    .;cllcccccc,...';ccldkkkOOOOOOOOOOOOkxdoc:cx00000KKK0OkkkkOOOOOOOOOOOOOOOOOOOkkkkOOOOOOO000000000OOOOOOkxoc;;;cllllllloddkO00OxdddoodooooooooooooooxOKXXXK00KKOkkdc'.                                                            ,xo;.                  
//                                                   .'.,;;,,;;:c:'...'::cldxxkkOOOOOO000Okxdllc;:dOOOO0OkdddxxxxxxxxkkkkkkkkkkkkkkkkkkkkxkkkOOOO0000000000O000OOkkxooooooodkkxxOOOOkkxddxkkxdddddooooodk0KXKK0kkxxdxdl'.                                                              lkl:'.                 
//                                                   ,l;;::;;;;;;:,....,::clddxxkkkkOOkkkkxdooooolldkkkxdodddddddddddddddddxxxkkkkkkkkkkkkxxxxxxkkOOOOOOOOOOO000000kxoooolooddxxkxddxkOOOkdodooddooodxOOOOkkxxddxxkkxdc'                                                              .xkl:,.                 
//                                                   ;oc:llllllcccc;'...';:loddxxxxxxxxkkkkkxxdoooodxkdoodddddddddoooollllllllllllllooodxkkkkxxdxxxkkkkkkkOOOOOOOkkkkxdoolooolloxkkkxdodxxddxkO00KK00KKOxxxddoclkOOkkdo:.                                                             ;Okoc,.                 
//                                                   ;oc;;cooooooool:....';cooddddddddxxkkkkkOOkkxdoodddxxxxxxxxxxxdooollcc:::::;;;,,''',;:codxxxxxxxxxxxxkkkOOOOxddxkxdooooddoodxxxxxxOO0KXXXK00OOkkxxdl:,'.. ,kOkkxddo.                                                            .o0xoc,.                 
//                                                   ;olc,,;clooooool:'....',:ccldxxkkOO00OOOkxdlc:clccclcc:::::::ccccc:;;:::cloolloooolllc:;;coddxxxxxxxxkkxxdddolcodkkxdoodxxxk0KK0KK000Okkdolc:;,'...      .ckxkkdoxd;.                                                           'kOkdc'.                 
//                                                   ,lolc:;;:llllllol:,.......'',;;:::::cc:;;:ccclc;'....,:lodxkkkkkkOd;:lddkOOkkkOkxooooool::coddddxxxxxxkkxo:;cddccoddl;;lxkxxkkxdolcc:,'....              .dkxxxloxxc.                                                           :OOkdc'                  
//                                                   .collcc::cllllllll:,'....';:::ccc:::;;'.,lol:loolc:cxKXXXXXXXKKKKKd;;looxkkkOOOkdooooooolc::cloodxkkkxdoc,',col;,',;,...',,,;:cc:,'..                    ;xkxkdclxkd'                                                          .o0Okdc.                  
//                                                   .:oollllccloooollll:,........',,,;;::c:;;::,,ldddxkkOOO0KKKKKKKKKOc.;lcldxkOOkkxdlllooooolc:;;;:cldddl,'...':;'............'...'..                      .lkxkkl;lxkx:.                                                         ,kOOOd:.                  
//                                                .. .cllollllllloooooool;'.....'......'',,,,,,,;:coodxxxxxxkO00KKOdooc'.'::cdooollllc:::ccclccc:;,..........   .......                                ..    'dkxkx;'cdkkl.                                                         cOOOOd;.                  
//                    'ld; .:dl.  .:l.            ;l',::clolllllllloolcllc;...'xk'..........''',;::cloooodddddxkOOockk;. ..';;,.........,:::::;;,'..               'xk'                               .l;    :kkkkd'.;lxkx;.                                                       .cxxkOd,                   
//                     :Xd. .kK,  .oc  ...        ...';,,;c:::::cc::::xkc::'...d0,.'......'....'',,,;:::::cc::lddxl;kO,...   ....   ....','',,,'''.  ....   ..     .x0'   ...    ....   ....  .  ..    ..  ..;llldc..':clc;.     .  ..  ...     ...    .. ..   ..     ...   .. ..  .lOxloc'...                
//                     .oXc 'kNk. lo..c:,lx:     .dk,.l0c.,dx',dl,ld,;00c:c:'..dKl;dk; ,xl,od..cOo..:d;'ll;ckd::ooc;kKl:dk, ,xc,do..oOocokd';kklcdk:.:Od;. .dc.    .x0' ,l:;ox,.oo,lk;.;kxll:cOd:cxo. :Ol.'xkc:dkc..oo,cxd:.   .:Od::xxc:lkl. ;l;,ld,.;kx::dkc:lxo. ;c;:xx,,kx::dx'.dNx;:ol,cd'               
//                      .k0:ollXdcd. dO;.,c:.     dK; lXo..dO''xkolc.'Ok,;llc..dK, ,Ko 'lc,xK; .o0;.o: c0l',co:;ll:,k0, ;Ko 'l:;kK, oXc  lNl.kO' .kK, c00c.co.     .x0'.Ox'.,l,.:c,lXd '0k.  ;Xd  dK, ,Kd..xO;.cXd :Xo .kO:..   ,Kd. lNl .kO.:Xl  .xK,'0k. :Xo  dK,,0o..:l'.Ok. :Ko.lXd,:dkoc:.               
//                       ,0Xo..oXO,  dK:  .,.     dK; cXl..xO'':;ck0;.Ok,,cll,.o0' '0o :k:.oK;  .x0x:. :Ko...::;:c;,k0' ,Ko.ck:.xK; oX;  :Kc.kO. .dO'  lKOko.      .x0'.kO,  '',xo.:Xd.'0x.  ;Ko  dK, ,Kd .xk;'cKo .dx,,l:::.   ,Kd  cXc .xO.:Xd.  dK,'0x. :Xl  dK,,0x.  ,..Ox. ;Ko.lXd,c;,:x0:               
//                        cd.  .dc   .okdll,      dK; .dx::xk;:xc,cd;.okl:::c;,dk;.;ko.cko;oOl.  .xl. ..ckxooc',;;,;xk;.:Ol.lkl;dOc.oNd',lc..OKc':o,   ..d0,       .dk; 'dkolc',kd;ckx,;kx'  :Oo..oO;.;Od.'dk:,lOo.'kOoolol:'   :Oo..l0c.'xk,.;dl,:l,.,kd..c0l..dO;.;xxolc.,kx'.cOo,:kxc:ol':d,               
//                                     ...     .. oO.   ....'',,;;;;;;;;;;::::;,'...... ...... .................',,,,;;'...  ..  .  oXc..   .kO,..   ..':o:        ....   ...    .. .. ....  ........ .....;clll:..ld:',;dkc,.  ........ ....   ...   .............   ...  ......,lolooo,....                 
//                                             ,l:c,      .........'',,;;::ccccc;'..... ...........................''''.           .lk:.    'dd,    .:oll,                                                .oxxkxc..:ol:::cclc.                                                   ;xxxOOx'                                                                  ..        ..          ......'',;::,............................ .....              ....     ....      .                                                   ,dddxd,    ....,ldo'                                                  .cxdkkOo.                     
//